### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by birby0** [Xpndable/DotUI#1]
Hello! I was wondering if it would be possible to add the option to change the menu color from pink to a different color. Other than that, this has been absolutely amazing for me. Thank you!

**Comment by Xpndable** [comment]
I have no immediate plans to make this possible - people are free to fork the code and change colors and images if they choose to, locations and information:
Images are [here](https://github.com/Xpndable/DotUI/tree/main/skeleton/.system/res)
Color values are [here](https://github.com/Xpndable/DotUI/blob/0ae18c1dcabad42db584d4f7dbc6c49fa51ff137/src/common/common.h#L39) and [here](https://github.com/Xpndable/DotUI/blob/0ae18c1dcabad42db584d4f7dbc6c49fa51ff137/src/say/main.c#L11)
