### ISSUE TITLE
PC Engine CD Games

### ISSUE THREAD

**Issue by gregmariotti** [Xpndable/DotUI#12]
i have the bios, but can't get the following to work
Turbo CD/PC Engine CD Games

thanks

**Comment by Xpndable** [comment]
Which games have you tried so I can replicate the issue?

**Comment by gregmariotti** [comment]
every chd and bin/cue file i’ve tried. us or japanese .

**Comment by gregmariotti** [comment]
working now....i had the wrong bios file..sorry
