### ISSUE TITLE
Menu button issue

### ISSUE THREAD

**Issue by alxv2016** [Xpndable/DotUI#23]
I’ve merged your latest code with the updates to the brightness and volume control. There’s a bug now with this as the in-game menu does not stay open, it no longer toggles and a user requires to hold it down to have it stay open.

**Comment by Xpndable** [comment]
The only thing I can find between your code and mine is that you might not have the patched code of SDL-1.2 to map the volume buttons to software keys?

**Comment by alxv2016** [comment]
> The only thing I can find between your code and mine is that you might not have the patched code of SDL-1.2 to map the volume buttons to software keys?

I've tested out your build seems like it isn't a bug, works all good.
