### ISSUE TITLE
Contrast and brightness option...  

### ISSUE THREAD

**Issue by ALTITUDE67** [Xpndable/DotUI#3]
Hello,
Thank you for your adaptation on the Mini Plus, it's really great. Can you tell me how to change the contrast, brightness, etc... and can you include an action replay mode in the different emulators?
Otherwise, great job, you are top and the system is fast and bug-free for me.
Thank you.

**Comment by Xpndable** [comment]
Brightness is controlled by holding START and tapping the L or R buttons.

Image calibration can still be done from the stock OS (hue, luminance, saturation, contrast). Power off the device, remove the SD card, power the device on, go to settings, go to color. As these settings are designed to be permanent once calibrated, there aren't any immediate plans to include this functionality in DotUI.
