### ISSUE TITLE
Is it possible to add arcade games?

### ISSUE THREAD

**Issue by alxv2016** [Xpndable/DotUI#4]
New to miniui and was curious if there’s a way to emulate arcade games?

**Comment by Xpndable** [comment]
Arcade emulation is a task we are leaving to OnionOS. The complexity of arcade emulation doesn't fit with the simple implementation idea for DotUI officially.

There are migrated paks from MiniUI that third-parties have created for this functionality on their own, but they aren't officially supported.

https://github.com/tiduscrying/MiniUI-Extra-Extras
